version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genesis-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
    networks:
      - genesis
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: genesis-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - genesis
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: genesis-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - genesis
    links:
      - app

networks:
  genesis:
    driver: bridge

volumes:
  vendor:
  dbdata:
